---
layout: post
title: Handling Errors in Go
network: digitalocean
date: July 22, 2019 at 08:35PM
url: https://www.digitalocean.com/community/tutorials/handling-errors-in-go
image: http://ifttt.com/images/no_image_card.png
tags: docker
feedtitle: DigitalOcean Community Tutorials
feedurl: https://www.digitalocean.com/community/tutorials
author: DigitalOcean
---
<p>Robust code needs to react correctly to unexpected circumstances like bad user input, faulty network connections, and failing disks. <em>Error handling</em> is the process of identifying when your program is in an unexpected state, and taking steps to record diagnostic information for later debugging.</p>

<p>Unlike other languages that require developers to handle errors with specialized syntax, errors in Go are values with the type <code>error</code> returned from functions like any other value. To handle errors in Go, we must examine these errors that functions could return, decide if an error has occurred, and take proper action to protect data and tell users or operators that the error occurred.</p>

<h2 id="creating-errors">Creating Errors</h2>

<p>Before we can handle errors, we need to create some first. The standard library provides two built-in functions to create errors: <code>errors.New</code> and <code>fmt.Errorf</code>. Both of these functions allow you to specify a custom error message that you can later present to your users.</p>

<p><code>errors.New</code> takes a single argument—an error message as a string that you can customize to alert your users what went wrong.</p>

<p>Try running the following example to see an error created by <code>errors.New</code> printed to standard output:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
)

func main() {
    err := errors.New("barnacles")
    fmt.Println("Sammy says:", err)
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>Sammy says: barnacles
</code></pre>
<p>We used the <code>errors.New</code> function from the standard library to create a new error message with the string <code>"barnacles"</code> as the error message. We've followed convention here by using lowercase for the error message as the <a href="https://github.com/golang/go/wiki/CodeReviewComments#error-strings">Go Programming Language Style Guide</a> suggests.</p>

<p>Finally, we used the <code>fmt.Println</code> function to combine our error message with <code>"Sammy says:"</code>.</p>

<p>The <code>fmt.Errorf</code> function allows you to dynamically build an error message. Its first argument is a string containing your error message with placeholder values such as <code>%s</code> for a string and <code>%d</code> for an integer. <code>fmt.Errorf</code> interpolates the arguments that follow this formatting string into those placeholders in order:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "fmt"
    "time"
)

func main() {
    err := fmt.Errorf("error occurred at: %v", time.Now())
    fmt.Println("An error happened:", err)
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>An error happened: Error occurred at: 2019-07-11 16:52:42.532621 -0400 EDT m=+0.000137103
</code></pre>
<p>We used the <code>fmt.Errorf</code> function to build an error message that would include the current time. The formatting string we provided to <code>fmt.Errorf</code> contains the <code>%v</code> formatting directive that tells <code>fmt.Errorf</code> to use the default formatting for the first argument provided after the formatting string. That argument will be the current time, provided by the <code>time.Now</code> function from the standard library. Similarly to the earlier example, we combine our error message with a short prefix and print the result to standard output using the <code>fmt.Println</code> function.</p>

<h2 id="handling-errors">Handling Errors</h2>

<p>Typically you wouldn't see an error created like this to be used immediately for no other purpose, as in the previous example. In practice, it's far more common to create an error and return it from a function when something goes wrong. Callers of that function will then use an <code>if</code> statement to see if the error was present or <code>nil</code>—an uninitialized value.</p>

<p>This next example includes a function that always returns an error. Notice when you run the program that it produces the same output as the previous example even though a function is returning the error this time. Declaring an error in a different location does not change the error's message.</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
)

func boom() error {
    return errors.New("barnacles")
}

func main() {
    err := boom()

    if err != nil {
        fmt.Println("An error occurred:", err)
        return
    }
    fmt.Println("Anchors away!")
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>An error occurred: barnacles
</code></pre>
<p>Here we define a function called <code>boom()</code> that returns a single <code>error</code> that we construct using <code>errors.New</code>. We then call this function and capture the error with the line <code>err := boom()</code>.<br>
Once we assign this error, we check to see if it was present with the <code>if err != nil</code> conditional. Here the conditional will always evaluate to <code>true</code>, since we are always returning an <code>error</code> from <code>boom()</code>.</p>

<p>This won't always be the case, so it's good practice to have logic handling cases where an error is not present (<code>nil</code>) and cases where the error is present. When the error is present, we use <code>fmt.Println</code> to print our error along with a prefix as we have done in earlier examples. Finally, we use a <code>return</code> statement to skip the execution of <code>fmt.Println("Anchors away!")</code>, since that should only execute when no error occurred.</p>

<p><span class='note'><strong>Note:</strong> The <code>if err != nil</code> construction shown in the last example is the workhorse of error handling in the Go programming language. Wherever a function could produce an error, it's important to use an <code>if</code> statement to check whether one occurred. In this way, idiomatic Go code naturally has its <a href="https://en.wikipedia.org/wiki/Happy_path">"happy path"</a> logic at the first indent level, and all the "sad path" logic at the second indent level.<br></span></p>

<p>If statements have an optional assignment clause that can be used to help condense calling a function and handling its errors.</p>

<p>Run the next program to see the same output as our earlier example, but this time using a compound <code>if</code> statement to reduce some boilerplate:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
)

func boom() error {
    return errors.New("barnacles")
}

func main() {
    if err := boom(); err != nil {
        fmt.Println("An error occurred:", err)
        return
    }
    fmt.Println("Anchors away!")
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>An error occurred: barnacles
</code></pre>
<p>As before, we have a function, <code>boom()</code>, that always returns an error. We assign the error returned from <code>boom()</code> to <code>err</code> as the first part of the <code>if</code> statement. In the second part of the <code>if</code> statement, following the semicolon, that <code>err</code> variable is then available. We check to see if the error was present and print our error with a short prefix string as we've done previously.</p>

<p>In this section, we learned how to handle functions that only return an error. These functions are common, but it's also important to be able to handle errors from functions that can return multiple values.</p>

<h2 id="returning-errors-alongside-values">Returning Errors Alongside Values</h2>

<p>Functions that return a single error value are often those that effect some stateful change, like inserting rows to a database. It's also common to write functions that return a value if they completed successfully along with a potential error if that function failed. Go permits functions to return more than one result, which can be used to simultaneously return a value and an error type.</p>

<p>To create a function that returns more than one value, we list the types of each returned value inside parentheses in the signature for the function. For example, a <code>capitalize</code> function that returns a <code>string</code> and an <code>error</code> would be declared using <code>func capitalize(name string) (string, error) {}</code>. The <code>(string, error)</code> part tells the Go compiler that this function will return a <code>string</code> and an <code>error</code>, in that order.</p>

<p>Run the following program to see the output from a function that returns both a <code>string</code> and an <code>error</code>:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
    "strings"
)

func capitalize(name string) (string, error) {
    if name == "" {
        return "", errors.New("no name provided")
    }
    return strings.ToTitle(name), nil
}

func main() {
    name, err := capitalize("sammy")
    if err != nil {
        fmt.Println("Could not capitalize:", err)
        return
    }

    fmt.Println("Capitalized name:", name)
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>Capitalized name: SAMMY
</code></pre>
<p>We define <code>capitalize()</code> as a function that takes a string (the name to be capitalized) and returns a string and an error value. In <code>main()</code>, we call <code>capitalize()</code> and assign the two values returned from the function to the <code>name</code> and <code>err</code> variables by separating them with commas on the left-hand side of the <code>:=</code> operator. After this, we perform our <code>if err != nil</code> check as in earlier examples, printing the error to standard output using <code>fmt.Println</code> if the error was present. If no error was present, we print <code>Capitalized name: SAMMY</code>.</p>

<p>Try changing the string <code>"sammy"</code> in <code>name, err := capitalize("sammy")</code> to the empty string <code>("")</code> and you'll receive the error <code>Could not capitalize: no name provided</code> instead.</p>

<p>The <code>capitalize</code> function will return an error when callers of the function provide an empty string for the <code>name</code> parameter. When the <code>name</code> parameter is not the empty string, <code>capitalize()</code> uses <code>strings.ToTitle</code> to capitalize the <code>name</code> parameter and returns <code>nil</code> for the error value.</p>

<p>There are some subtle conventions that this example follows that is typical of Go code, yet not enforced by the Go compiler. When a function returns multiple values, including an error, convention requests that we return the <code>error</code> as the last item. When returning an <code>error</code> from a function with multiple return values, idiomatic Go code also will set each non-error value to a <em>zero value</em>. Zero values are, for example, an empty string for strings, <code>0</code> for integers, an empty struct for struct types, and <code>nil</code> for interface and pointer types, to name a few. We cover zero values in more detail in our <a href="https://www.digitalocean.com/community/tutorials/how-to-use-variables-and-constants-in-go#zero-values">tutorial on variables and constants</a>.</p>

<h3 id="reducing-boilerplate">Reducing boilerplate</h3>

<p>Adhering to these conventions can become tedious in situations where there are many values to return from a function. We can use an <a href="https://en.wikipedia.org/wiki/Anonymous_function"><em>anonymous function</em></a> to help reduce the boilerplate. Anonymous functions are procedures assigned to variables. In contrast to the functions we have defined in earlier examples, they are only available within the functions where you declare them—this makes them perfect to act as short pieces of reusable helper logic.</p>

<p>The following program modifies the last example to include the length of the name that we're capitalizing. Since it has three values to return, handling errors could become cumbersome without an anonymous function to assist us:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
    "strings"
)

func capitalize(name string) (string, int, error) {
    handle := func(err error) (string, int, error) {
        return "", 0, err
    }

    if name == "" {
        return handle(errors.New("no name provided"))
    }

    return strings.ToTitle(name), len(name), nil
}

func main() {
    name, size, err := capitalize("sammy")
    if err != nil {
        fmt.Println("An error occurred:", err)
    }

    fmt.Printf("Capitalized name: %s, length: %d", name, size)
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>Capitalized name: SAMMY, length: 5
</code></pre>
<p>Within <code>main()</code>, we now capture the three returned arguments from <code>capitalize</code> as <code>name</code>, <code>size</code>, and <code>err</code>, respectively. We then check to see if <code>capitalize</code> returned an <code>error</code> by checking if the <code>err</code> variable was not equal to <code>nil</code>. This is important to do before attempting to use any of the other values returned by <code>capitalize</code>, because the anonymous function, <code>handle</code>, could set those to zero values. Since no error occurred because we provided the string <code>"sammy"</code>, we print out the capitalized name and its length.</p>

<p>Once again, you can try changing <code>"sammy"</code> to the empty string <code>("")</code> to see the error case printed (<code>An error occurred: no name provided</code>).</p>

<p>Within <code>capitalize</code>, we define the <code>handle</code> variable as an anonymous function. It takes a single error and returns identical values in the same order as the return values of <code>capitalize</code>. <code>handle</code> sets those values to zero values and forwards the <code>error</code> passed as its argument as the final return value. Using this, we can then return any errors encountered in <code>capitalize</code> by using the <code>return</code> statement in front of the call to <code>handle</code> with the <code>error</code> as its parameter.</p>

<p>Remember that <code>capitalize</code> must return three values all the time, since that's how we defined the function. Sometimes we don't want to deal with all the values that a function could return. Fortunately, we have some flexibility in how we can use these values on the assignment side.</p>

<h2 id="handling-errors-from-multi-return-functions">Handling Errors from Multi-Return Functions</h2>

<p>When a function returns many values, Go requires us to assign each to a variable. In the last example, we do this by providing names for the two values returned from the <code>capitalize</code> function. These names should be separated by commas and appear on the left-hand side of the <code>:=</code> operator. The first value returned from <code>capitalize</code> will be assigned to the <code>name</code> variable, and the second value (the <code>error</code>) will be assigned to the variable <code>err</code>. Occasionally, we're only interested in the error value. You can discard any unwanted values that functions return using the special <code>_</code> variable name.</p>

<p>In the following program, we've modified our first example involving the <code>capitalize</code> function to produce an error by passing in the empty string <code>("")</code>. Try running this program to see how we're able to examine just the error by discarding the first returned value with the <code>_</code> variable:</p>
<pre class="code-pre "><code class="code-highlight language-go">package main

import (
    "errors"
    "fmt"
    "strings"
)

func capitalize(name string) (string, error) {
    if name == "" {
        return "", errors.New("no name provided")
    }
    return strings.ToTitle(name), nil
}

func main() {
    _, err := capitalize("")
    if err != nil {
        fmt.Println("Could not capitalize:", err)
        return
    }
    fmt.Println("Success!")
}
</code></pre><pre class="code-pre "><code langs=""><div class="secondary-code-label " title="Output">Output</div>Could not capitalize: no name provided
</code></pre>
<p>Within the <code>main()</code> function this time, we assign the capitalized name (the <code>string</code> returned first) to the underscore variable (<code>_</code>). At the same time, we assign the <code>error</code> returned by <code>capitalize</code> to the <code>err</code> variable. We then check if the error was present in the <code>if err != nil</code> conditional. Since we have hard-coded an empty string as an argument to <code>capitalize</code> in the line <code>_, err := capitalize("")</code>, this conditional will always evaluate to <code>true</code>. This produces the output <code>"Could not capitalize: no name provided"</code> printed by the call to the <code>fmt.Println</code> function within the body of the <code>if</code> statement. The <code>return</code> after this will skip the <code>fmt.Println("Success!")</code>.</p>

<h2 id="conclusion">Conclusion</h2>

<p>We've seen many ways to create errors using the standard library and how to build functions that return errors in an idiomatic way. In this tutorial, we've managed to successfully create various errors using the standard library <code>errors.New</code> and <code>fmt.Errorf</code> functions. In future tutorials, we'll look at how to create our own custom error types to convey richer information to users.</p>
